### PR TITLE
Implementation of AdaptSize

### PR DESCRIPTION
**Pull request by yipkeikwok**
Sample Command Line
./webcachesim test.tr AdaptSize 1000

### CODE REVIEW

**Comment by dasebe** [comment]
Overall this looks good, and I hoping to look at it with more care towards the end of the week.

**Comment by quovadim** [comment]
In function admit of adaptsize clearly a mistake. According to the paper, probability should be -size/c while in the code it is size/c and moreover, size and c are not double, so the correct code is sampling from uniform_real_distribution(0, 1) and calculate the probability as std::exp(-1 * double(req->getSize())/c);

**Comment by yipkeikwok** [comment]
Good catch @WVadim 
Now, it is fixed. Thank you. 
> 
> In function admit of adaptsize clearly a mistake. According to the paper, probability should be -size/c while in the code it is size/c and moreover, size and c are not double, so the correct code is sampling from uniform_real_distribution(0, 1) and calculate the probability as std::exp(-1 * double(req->getSize())/c);

**Comment by dasebe** [comment]
I've made a few minor revisions and tested the implemented. Merged into testing. Master to follow.

**Pull request merged**
